# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sgpt < Formula
  desc ""
  homepage "https://k8sgpt.ai"
  version "0.4.35"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.35/k8sgpt_Darwin_x86_64.tar.gz"
      sha256 "a7c3620e5d85e57142322c66d6de0ac6ecf2810fe7d71f3dddb4d0c2e8c35884"

      define_method(:install) do
        bin.install "k8sgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.35/k8sgpt_Darwin_arm64.tar.gz"
      sha256 "d051f88cb8acd11c7b55e74523cd6a9658a861ead05ede15ee2658fe628d226e"

      define_method(:install) do
        bin.install "k8sgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.35/k8sgpt_Linux_x86_64.tar.gz"
      sha256 "5497af82a3a38d54449f287464f7a6993bef5daa301f0c30a3a3a4667a9353b6"
      define_method(:install) do
        bin.install "k8sgpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.35/k8sgpt_Linux_arm64.tar.gz"
      sha256 "060c5cf667ec7d73e779f495ab7d8e6d0db0d092271a4cef6b0d5fe35b0a991a"
      define_method(:install) do
        bin.install "k8sgpt"
      end
    end
  end
end
