# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sgpt < Formula
  desc ""
  homepage "https://k8sgpt.ai"
  version "0.4.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.10/k8sgpt_Darwin_x86_64.tar.gz"
      sha256 "4140b9a3b2f1c74aa487852f8468330e25bf80f1ee1b97f00a53a0eb233e23f5"

      def install
        bin.install "k8sgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.10/k8sgpt_Darwin_arm64.tar.gz"
      sha256 "67e70629e793d4e1d8bb3a6f99e23915e1f8458761dd76a78b4c5332e60b4d39"

      def install
        bin.install "k8sgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.10/k8sgpt_Linux_x86_64.tar.gz"
        sha256 "e7b1ae73f8d5825321d438eedd0e7dc0606f33575a6c30b68989b35318b60c71"

        def install
          bin.install "k8sgpt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/k8sgpt-ai/k8sgpt/releases/download/v0.4.10/k8sgpt_Linux_arm64.tar.gz"
        sha256 "c4066e3603b96e4582a878178ecfb8046cc995b6f29eb8909c1c969a685de052"

        def install
          bin.install "k8sgpt"
        end
      end
    end
  end
end
